version: 0.2

env:
  variables:
    S3_BUCKET_NAME: cicd-sam-test-artifacts-bucket # S3バケット名を指定

phases:
  install:
    commands:
      - pip install aws-sam-cli
  pre_build:
    commands:
      - sam validate
      - sam local invoke --no-event MyFunction
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket $S3_BUCKET_NAME

artifacts:
  files:
    - packaged.yaml
